### ISSUE TITLE
How to find closest embedding vectors?

### ISSUE THREAD

**Issue by smith-co** [daveshap/VDBLITE#1]
Thanks for the fantastic utility function. I have exactly this requirement where I have to search for matching embedding.

I have 100K known embedding i.e. 

    [emb_1, emb_2, ..., emb_100000]

Each of this embedding is derived from GPT-3 sentence embedding with dimension `2048`. My task is given an embedding(`embedding_new`) find the closest 10 embedding from the above `100k` embedding. 

The way I am approaching this problem was brute force. Every time a query asks to find the closest embeddings, I compare `embedding_new` with `[emb_1, emb_2, ..., emb_100000]` and get the similarity score. Then I do quicksort of the similarity score to get the top `10` closest embedding. Alternatively, I have also thought about using Faiss. 

However, VDBLITE seems to be perfect match. But I don't understand how to find keep the mapping for VDBLITE as it only keeps vectors.

```
    dimension = 768  # dimensions of each vector

    corpus = ["tom loves candy",
                    "this is a test"
                    "hello world"
                    "jerry loves programming"]

    corpus_emddings = get_embeddings(corpus)

    for vector in corpus_emddings:
        info = {'vector': vector, 'time': time(), 'uuid': str(uuid4())}
        vdb.add(info)
````

Now lets say I need to find the close match for "jerry loves candy". How can I get the closest sentence using VDBLITE?

Can you please provide an example?

**Comment by daveshap** [comment]
You use the search function
