### ISSUE TITLE
Cannot run Vdb.load 

### ISSUE THREAD

**Issue by nashid** [daveshap/VDBLITE#10]
When I attempt to load saved embedding, its crashes:

```
vdb.load('embeddings.csv')
```

Error trace:

```
  File "/XXXXXXX/lib/python3.9/site-packages/vdblite/__init__.py", line 86, in load
    self.data = pickle.load(infile)
io.UnsupportedOperation: read
```

**Comment by daveshap** [comment]
You're not using it correctly. Please see documentation.

**Comment by daveshap** [comment]
You can only load a .VDB file that was previously saved, not a CSV.

**Comment by nashid** [comment]
@daveshap thats a typo on my end. There is a bug in the load function of vdblite.

I had to modify into following to get the DB working:

```
    def load(self, filepath):
        with open(filepath, 'rb') as infile:
            self.data = pickle.load(infile)
```
