### ISSUE TITLE
VDBLITE is completely broken and corrupt data

### ISSUE THREAD

**Issue by nashid** [daveshap/VDBLITE#11]
@daveshap When I attempt to load `saved embedding`, its crashes:

```
vdb.load('embeddings.vdb')
```

The reason steps from bug here:
https://github.com/daveshap/VDBLITE/blob/main/vdblite/__init__.py#L85

You should modify according to the following not to corrupt previous files:
```
    def load(self, filepath):
        with open(filepath, 'rb') as infile:
            self.data = pickle.load(infile)

```

**Comment by daveshap** [comment]
Oops, thanks for finding that, I will fix momentarialy.

**Comment by daveshap** [comment]
Okay, should be fixed, please upgrade to latest version https://pypi.org/project/vdblite/0.1.4/
