### ISSUE TITLE
vdb.search is stuck

### ISSUE THREAD

**Issue by ramsey-coding** [daveshap/VDBLITE#12]
I have loaded around `350K` vectors in [VDBLITE](https://github.com/daveshap/VDBLITE).

Following that I did a semantic search for similar vector using:

```
vdb.search(search_embedding, 'vector', 100)
```

Each of the API call is taking ~2seconds which makes it practically unusable. 

```
/site-packages/vdblite/__init__.py", line 30, in search
    score = np.dot(i[field], vector)
  File "<__array_function__ internals>", line 180, in dot
```

I got super excited about it after watching your YouTube video.  This is a great library and has a lot of potential. I just wish it was little more tested and more functional 😢 😢 😢  

@daveshap can you please help? Really really looking forward to your help.

**Comment by ramsey-coding** [comment]
@daveshap can you please help? 🙏

**Comment by daveshap** [comment]
It will get optimized when I get around to it. This isn't an actual issue. Please use the discussion tab.
