### ISSUE TITLE
Memory usage by VDBLITE

### ISSUE THREAD

**Issue by smith-co** [daveshap/VDBLITE#3]
I would be loading about 500K records with Ada embedding (1024 dimensions). Is it even possible to load it in a MAC machine with 16GB memory.

Any idea what would be memory usage by VDBLITE?

**Comment by daveshap** [comment]
This is not a legitimate issue.

**Comment by smith-co** [comment]
@daveshap you are the author of this library and I am simply asking a question about the usage of this library. Can you please provide any feedback 🙏?

**Comment by daveshap** [comment]
I created a discussions page.
